spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/_db
    driver-class-name: org.postgresql.Driver
    username: _user
    password: 2381012
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect